### ISSUE TITLE
Android crash report in ServerListActivity

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#74]
java.lang.NullPointerException
at dk.bearware.gui.ServerListActivity.onCmdMyselfLoggedIn(ServerListActivity.java:538)
at dk.bearware.events.TeamTalkEventHandler.processEvent(TeamTalkEventHandler.java:132)
at dk.bearware.backend.TeamTalkService$2.onTick(TeamTalkService.java:264)
at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:124)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5086)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)

**Comment by poretsky** [comment]
Fixed in 7bc5a3266ffc8deea22416f5b0001ff67ef811b8
