### ISSUE TITLE
Android crash, invalid fragment

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#75]
java.lang.RuntimeException: Unable to start activity ComponentInfo{dk.bearware.gui/dk.bearware.gui.PreferencesActivity}: java.lang.RuntimeException: Subclasses of PreferenceActivity must override isValidFragment(String) to verify that the Fragment class is valid! dk.bearware.gui.PreferencesActivity has not checked if fragment dk.bearware.gui.PreferencesActivity$GeneralPreferenceFragment is valid.
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464)
at android.app.ActivityThread.access$900(ActivityThread.java:172)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5653)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: Subclasses of PreferenceActivity must override isValidFragment(String) to verify that the Fragment class is valid! dk.bearware.gui.PreferencesActivity has not checked if fragment dk.bearware.gui.PreferencesActivity$GeneralPreferenceFragment is valid.
at android.preference.PreferenceActivity.isValidFragment(PreferenceActivity.java:1334)
at android.preference.PreferenceActivity.switchToHeaderInner(PreferenceActivity.java:1647)
at android.preference.PreferenceActivity.switchToHeader(PreferenceActivity.java:1687)
at android.preference.PreferenceActivity.onCreate(PreferenceActivity.java:784)
at android.app.Activity.performCreate(Activity.java:5539)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368)

**Comment by poretsky** [comment]
Fixed in c8eaa16fb93becd3ff01463c99a21437c3ee4c26
