### ISSUE TITLE
Android crash, activity failed to resume

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#76]
java.lang.RuntimeException: Unable to resume activity {dk.bearware.gui/dk.bearware.gui.ServerListActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { cmp=dk.bearware.gui/.ServerEntryActivity (has extras) }} to activity {dk.bearware.gui/dk.bearware.gui.ServerListActivity}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2621)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2649)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2122)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3558)
at android.app.ActivityThread.access$800(ActivityThread.java:134)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1224)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4867)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { cmp=dk.bearware.gui/.ServerEntryActivity (has extras) }} to activity {dk.bearware.gui/dk.bearware.gui.ServerListActivity}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at android.app.ActivityThread.deliverResults(ActivityThread.java:3187)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2608)
... 13 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at java.util.Vector.arrayIndexOutOfBoundsException(Vector.java:907)
at java.util.Vector.removeElementAt(Vector.java:805)
at dk.bearware.gui.ServerListActivity.onActivityResult(ServerListActivity.java:173)
at android.app.Activity.dispatchActivityResult(Activity.java:5231)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3183)

**Comment by poretsky** [comment]
Fixed in f4fc747c3cd9280f2791218c1e4893095c1afc48
