### ISSUE TITLE
Crash in ServerEntryActivity

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#79]
Preference needs to be check for null prior. Was fix on ServerEntryActivity.java:183 but forgot ServerEntryActivity.java:199.

java.lang.NullPointerException
at dk.bearware.gui.ServerEntryActivity.showServer(ServerEntryActivity.java:199)
at dk.bearware.gui.ServerEntryActivity.onStart(ServerEntryActivity.java:108)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1166)
at android.app.Activity.performStart(Activity.java:5264)
at android.app.Activity.performRestart(Activity.java:5315)
at android.app.ActivityThread.handleSleeping(ActivityThread.java:3167)
at android.app.ActivityThread.access$2700(ActivityThread.java:138)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1383)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4929)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
at dalvik.system.NativeStart.main(Native Method)

**Comment by bear101** [comment]
Fixed.

**Comment by bear101** [comment]
Commit 654776e3bfa052b94d03587b928706c1bdfc111e
