### ISSUE TITLE
Crash due to username being null

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#84]
java.lang.NullPointerException: szUsername is null
at dk.bearware.TeamTalkBase.doLogin(Native Method)
at dk.bearware.TeamTalkBase.doLogin(TeamTalkBase.java:389)
at dk.bearware.backend.TeamTalkService.onConnectSuccess(TeamTalkService.java:333)
at dk.bearware.events.TeamTalkEventHandler.processEvent(TeamTalkEventHandler.java:95)
at dk.bearware.backend.TeamTalkService$2.onTick(TeamTalkService.java:264)
at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:133)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5274)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)

**Comment by bear101** [comment]
Fixed in Utils.java commit 0d5699bd4a04759e02e32aafc7c1ad3053ccfda2
