### ISSUE TITLE
Crash due to ip-address being null

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#85]
java.lang.NullPointerException: szHostAddress is null
at dk.bearware.TeamTalkBase.connect(Native Method)
at dk.bearware.TeamTalkBase.connect(TeamTalkBase.java:340)
at dk.bearware.backend.TeamTalkService.reconnect(TeamTalkService.java:189)
at dk.bearware.gui.ServerEntryActivity.onOptionsItemSelected(ServerEntryActivity.java:151)
at android.app.Activity.onMenuItemSelected(Activity.java:2808)
at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1104)
at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:741)
at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:884)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
at com.android.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:721)
at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:214)
at android.view.View.performClick(View.java:4754)
at android.view.View$PerformClick.run(View.java:19605)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5752)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)

**Comment by poretsky** [comment]
Fixed in aba868a8e55fa27024d20552806c11eb52a35551

**Comment by bear101** [comment]
Any idea how the IP-address can be null? In ServerEntry-class the IP-address is always assigned to an empty string.

I wonder if it's EditTextPreference.getText() which can return null if nothing is set? Checkout ServerEntryActivity.getServerEntry().

**Comment by bear101** [comment]
Fixed in Utils.java commit 0d5699bd4a04759e02e32aafc7c1ad3053ccfda2
