### ISSUE TITLE
Crash due to server-entry containing null

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#86]
java.lang.NullPointerException: Attempt to read from field 'java.lang.String dk.bearware.data.ServerEntry.servername' on a null object reference
at dk.bearware.gui.ServerListActivity.onCmdMyselfLoggedIn(ServerListActivity.java:538)
at dk.bearware.events.TeamTalkEventHandler.processEvent(TeamTalkEventHandler.java:132)
at dk.bearware.backend.TeamTalkService$2.onTick(TeamTalkService.java:264)
at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:133)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5944)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)

**Comment by poretsky** [comment]
It seems to be somewhat outdated. I cannot imagine a situation when such
crash could occur in the current version.

**Comment by bear101** [comment]
Fixed in Utils.java commit 0d5699bd4a04759e02e32aafc7c1ad3053ccfda2
