### ISSUE TITLE
Crash due to MediaButtonEvent

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#89]
java.lang.RuntimeException: Unable to start receiver dk.bearware.gui.MediaButtonEventReceiver: java.lang.NullPointerException
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2433)
at android.app.ActivityThread.access$1700(ActivityThread.java:142)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1279)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5062)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:657)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at dk.bearware.gui.MediaButtonEventReceiver.onReceive(MediaButtonEventReceiver.java:15)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2426)
... 10 more

**Comment by poretsky** [comment]
Fixed in 2a5b159172a530960f7881df1b72ce111aaf4fbb

**Comment by poretsky** [comment]
Sorry, it seems that I was wrong.
Fixed in 9c61e592170d4ffe8ac8b581c596ec99a8df7e0a

**Comment by bear101** [comment]
Not seen in a long time... cannot reproduce...

**Comment by Piciok** [comment]
I have recently managed to reproduce it by triggering the media event declared as an intent in the Manifest file of the app using the Start Intent app.

I can reproduce it on Android 5.0.2 running on a Huawei Honor 7.

What happens is that the connection to the server is cut.
  ----- Original Message -----
