### ISSUE TITLE
Crash in Preferences Activity

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#90]
java.lang.RuntimeException: Unable to start activity ComponentInfo{dk.bearware.gui/dk.bearware.gui.PreferencesActivity}: java.lang.IllegalArgumentException: Invalid fragment for this activity: dk.bearware.gui.PreferencesActivity$GeneralPreferenceFragment
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2328)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2386)
at android.app.ActivityThread.access$900(ActivityThread.java:169)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1277)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5476)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: Invalid fragment for this activity: dk.bearware.gui.PreferencesActivity$GeneralPreferenceFragment
at android.preference.PreferenceActivity.switchToHeaderInner(PreferenceActivity.java:1648)
at android.preference.PreferenceActivity.switchToHeader(PreferenceActivity.java:1687)
at android.preference.PreferenceActivity.onCreate(PreferenceActivity.java:784)
at android.app.Activity.performCreate(Activity.java:5473)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
... 11 more

**Comment by bear101** [comment]
Fixed in f29a9fa2d4c16c74b1a1903620ea36b7ee612d2d
